# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class ExampleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test = channel.unary_unary(
                '/example.Example/test',
                request_serializer=data__pb2.req.SerializeToString,
                response_deserializer=data__pb2.resp.FromString,
                )
        self.client_recv_stream = channel.unary_stream(
                '/example.Example/client_recv_stream',
                request_serializer=data__pb2.req.SerializeToString,
                response_deserializer=data__pb2.resp1.FromString,
                )


class ExampleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test(self, request, context):
        """最简单的传输方式
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_recv_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test': grpc.unary_unary_rpc_method_handler(
                    servicer.test,
                    request_deserializer=data__pb2.req.FromString,
                    response_serializer=data__pb2.resp.SerializeToString,
            ),
            'client_recv_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.client_recv_stream,
                    request_deserializer=data__pb2.req.FromString,
                    response_serializer=data__pb2.resp1.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Example', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Example(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Example/test',
            data__pb2.req.SerializeToString,
            data__pb2.resp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def client_recv_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/example.Example/client_recv_stream',
            data__pb2.req.SerializeToString,
            data__pb2.resp1.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
