# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x07\x65xample\"\x13\n\x03req\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x16\n\x04resp\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x17\n\x05resp1\x12\x0e\n\x06result\x18\x01 \x01(\t2h\n\x07\x45xample\x12%\n\x04test\x12\x0c.example.req\x1a\r.example.resp\"\x00\x12\x36\n\x12\x63lient_recv_stream\x12\x0c.example.req\x1a\x0e.example.resp1\"\x00\x30\x01\x62\x06proto3'
)




_REQ = _descriptor.Descriptor(
  name='req',
  full_name='example.req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='example.req.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=42,
)


_RESP = _descriptor.Descriptor(
  name='resp',
  full_name='example.resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='example.resp.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=66,
)


_RESP1 = _descriptor.Descriptor(
  name='resp1',
  full_name='example.resp1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='example.resp1.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['resp'] = _RESP
DESCRIPTOR.message_types_by_name['resp1'] = _RESP1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.req)
  })
_sym_db.RegisterMessage(req)

resp = _reflection.GeneratedProtocolMessageType('resp', (_message.Message,), {
  'DESCRIPTOR' : _RESP,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.resp)
  })
_sym_db.RegisterMessage(resp)

resp1 = _reflection.GeneratedProtocolMessageType('resp1', (_message.Message,), {
  'DESCRIPTOR' : _RESP1,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.resp1)
  })
_sym_db.RegisterMessage(resp1)



_EXAMPLE = _descriptor.ServiceDescriptor(
  name='Example',
  full_name='example.Example',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='test',
    full_name='example.Example.test',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='client_recv_stream',
    full_name='example.Example.client_recv_stream',
    index=1,
    containing_service=None,
    input_type=_REQ,
    output_type=_RESP1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name['Example'] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
