# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x04test\" \n\x03req\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x16\n\x04resp\x12\x0e\n\x06result\x18\x01 \x01(\t2,\n\x06\x42ibili\x12\"\n\x07helloyu\x12\t.test.req\x1a\n.test.resp\"\x00\x62\x06proto3'
)




_REQ = _descriptor.Descriptor(
  name='req',
  full_name='test.req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.req.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.req.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=53,
)


_RESP = _descriptor.Descriptor(
  name='resp',
  full_name='test.resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.resp.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['req'] = _REQ
DESCRIPTOR.message_types_by_name['resp'] = _RESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:test.req)
  })
_sym_db.RegisterMessage(req)

resp = _reflection.GeneratedProtocolMessageType('resp', (_message.Message,), {
  'DESCRIPTOR' : _RESP,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:test.resp)
  })
_sym_db.RegisterMessage(resp)



_BIBILI = _descriptor.ServiceDescriptor(
  name='Bibili',
  full_name='test.Bibili',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=123,
  methods=[
  _descriptor.MethodDescriptor(
    name='helloyu',
    full_name='test.Bibili.helloyu',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIBILI)

DESCRIPTOR.services_by_name['Bibili'] = _BIBILI

# @@protoc_insertion_point(module_scope)
