# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_pb2 as hello__pb2


class BibiliStub(object):
    """服务名，函数名
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.helloyu = channel.unary_unary(
                '/test.Bibili/helloyu',
                request_serializer=hello__pb2.req.SerializeToString,
                response_deserializer=hello__pb2.resp.FromString,
                )


class BibiliServicer(object):
    """服务名，函数名
    """

    def helloyu(self, request, context):
        """要写的函数,rpc 是定义的关键字
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibiliServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'helloyu': grpc.unary_unary_rpc_method_handler(
                    servicer.helloyu,
                    request_deserializer=hello__pb2.req.FromString,
                    response_serializer=hello__pb2.resp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Bibili', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bibili(object):
    """服务名，函数名
    """

    @staticmethod
    def helloyu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Bibili/helloyu',
            hello__pb2.req.SerializeToString,
            hello__pb2.resp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
